# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 15:28
from __future__ import unicode_literals

import broadcasts.models
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/mayank/wd/django1.9_python_3.x/projects/libtech.info/CDN/protected'), upload_to=broadcasts.models.download_media_location)),
                ('title', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(default='Enter description here')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=9.99, max_digits=100, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, default=6.99, max_digits=100, null=True)),
                ('managers', models.ManyToManyField(blank=True, related_name='broadcast_managers', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyBroadcasts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broadcasts', models.ManyToManyField(blank=True, to='broadcasts.Broadcast')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'My Broadcasts',
                'verbose_name_plural': 'My Broadcasts',
            },
        ),
    ]
