# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-12 00:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workdetails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyWorkdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'My Workdetails',
                'verbose_name': 'My Workdetails',
            },
        ),
        migrations.CreateModel(
            name='Workdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('block_name', models.CharField(max_length=30)),
                ('block_code', models.CharField(max_length=3)),
                ('panchayat_name', models.CharField(max_length=40)),
                ('panchayat_code', models.CharField(max_length=3)),
                ('financial_year', models.CharField(max_length=2)),
                ('muster_index', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=256)),
                ('jobcard', models.CharField(max_length=30)),
                ('jobcard_number', models.PositiveSmallIntegerField()),
                ('muster_number', models.CharField(max_length=50)),
                ('work_code', models.CharField(max_length=40)),
                ('work_name', models.CharField(max_length=1024)),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('days_worked', models.PositiveSmallIntegerField()),
                ('day_wage', models.IntegerField()),
                ('total_wage', models.IntegerField()),
                ('account_number', models.CharField(max_length=25)),
                ('wagelist_number', models.CharField(max_length=20)),
                ('bank_or_po_name', models.CharField(max_length=40)),
                ('branch_name_or_po_address', models.CharField(max_length=40)),
                ('branch_or_po_code', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('credited_date', models.DateTimeField()),
                ('is_bank', models.BooleanField()),
                ('is_post', models.BooleanField()),
                ('rejection_reason', models.CharField(max_length=50)),
                ('fto_event_date', models.DateTimeField()),
                ('fto_event', models.CharField(max_length=2048)),
                ('fto_office', models.CharField(max_length=1024)),
                ('fto_field', models.CharField(max_length=2048)),
                ('update_date', models.DateTimeField()),
                ('create_date', models.DateTimeField()),
                ('fto_number', models.CharField(max_length=30)),
                ('fto_number_updated', models.BooleanField()),
                ('primary_account_holder', models.CharField(max_length=50)),
                ('payment_date', models.DateTimeField()),
                ('managers', models.ManyToManyField(blank=True, related_name='workdetail_managers', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='broadcast',
            name='managers',
        ),
        migrations.RemoveField(
            model_name='broadcast',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mybroadcasts',
            name='broadcasts',
        ),
        migrations.RemoveField(
            model_name='mybroadcasts',
            name='user',
        ),
        migrations.DeleteModel(
            name='Broadcast',
        ),
        migrations.DeleteModel(
            name='MyBroadcasts',
        ),
        migrations.AddField(
            model_name='myworkdetails',
            name='workdetails',
            field=models.ManyToManyField(blank=True, to='workdetails.Workdetail'),
        ),
    ]
