# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workdetails', '0002_auto_20160712_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdetail',
            name='fto_event_date',
            field=models.DateTimeField(null=True),
        ),
    ]
