# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workdetails', '0004_auto_20160713_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdetail',
            name='fto_event',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='workdetail',
            name='fto_field',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='workdetail',
            name='fto_office',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
