# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workdetails', '0007_auto_20160713_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdetail',
            name='credited_date',
            field=models.DateTimeField(null=True),
        ),
    ]
