# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workdetails', '0008_auto_20160713_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdetail',
            name='fto_number',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
