# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workdetails', '0009_auto_20160713_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='workdetail',
            name='is_closed',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='workdetail',
            name='remarks',
            field=models.CharField(default='Add your remarks here', max_length=30),
        ),
    ]
