# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-19 18:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0002_auto_20160719_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 19, 18, 49, 50, 688520, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
