# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-19 22:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0004_auto_20160720_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 19, 22, 44, 43, 187657, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
