# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='post',
            new_name='Blog',
        ),
    ]
